package com.buildit.rental.domain.model;

public enum POStatus {
    PENDING, REJECTED, OPEN, CLOSED, ACCEPTED, CANCELLED, PLANT_DISPATCHED, PLANT_DELIVERED, PLANT_REJECTED, PLANT_RETURNED, PAID, RETURNED
}
